### ISSUE TITLE
２０２３年１０月４日安全衛生委員会

### ISSUE THREAD

**Issue by toraaa74** [shiroi36/DXkaigi#26]
- セコムカード
セコムカードの配布にあたり、誓約書を作成

- 社用車の駐車方法
1年ごと交代制で駐車場の場所を決める
タッチパネルを1階に導入して、社用車の予約がすぐに見れるようにする

- インフルエンザ
感染者数は増加
9/25〜10/1の定点当たり報告数は　9.57
「10」が注意報・「30」が警報
致死率・重症化率はインフルエンザとコロナウイルスで同じくらい

- コロナウイルス
感染者数は減少
9/20以降　オミクロン株に対応したワクチンの接種開始
致死率・重症化率はインフルエンザとコロナウイルスで同じくらい

- プール熱
子どもに流行

- 喫煙所
2階の方から、たばこのにおいが辛いとの意見
1階の駐車スペースの一部を喫煙所にする

- 防災用品
水の保管期限が近いので買替予定
ペットボトルの長期保存水を買うかウォーターサーバーにするか検討
LEDのランタンの購入を検討

次回委員会日程　：　11/7　11：00～

次回委員会までにやること

- [x] ウォーターサーバーの見積
- [x] セコムカードの書類作成
- [x] シーツの購入
- [x] 管理計画書の防災をスライド

**Comment by toraaa74** [comment]
[安全衛生委員会議事録20231004.pdf](https://github.com/shiroi36/DXkaigi/files/13172402/20231004.pdf)

**Comment by ghost** [comment]
[セキュリティカードの取り扱いについて.pdf](https://github.com/shiroi36/DXkaigi/files/13434161/default.pdf)
[念書.pdf](https://github.com/shiroi36/DXkaigi/files/13434162/default.pdf)
[取扱説明書.pdf](https://github.com/shiroi36/DXkaigi/files/13434167/default.pdf)
